modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/franxie95/resocraft/issues"
[[mods]]
modId="resocraft"
version="${file.jarVersion}"
displayName="ResoCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/resocraft"
credits="Thanks for InsanityCraft goes to all the original mod devs! Without you guys, this dream would've never come true. Also, thanks to the community for being super supportive, that has kept this mod going!"
logoFile="log0o.png"
authors="franxie95"
description='''resurection of a bunch of old mods'''
[[dependencies.resocraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.resocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
